runtime: python39
entrypoint: gunicorn -b :$PORT main:app

instance_class: F2

env_variables:
MYSQL_HOST : 34.101.128.44
MYSQL_USER : myuser
MYSQL_PASSWORD: mypass
MYSQL_DB: meatu

automatic_scaling:
  target_cpu_utilization: 0.65

handlers:
- url: /.*
  script: auto